version: "3.9"

services:
  postgres:
    image: postgres
    container_name: bun-db
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"